//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkinCareWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionData
    {
        public int Id { get; set; }
        public Nullable<int> UvRange { get; set; }
        public Nullable<int> DescriptionId { get; set; }
        public string WeatherDescription { get; set; }
    
        public virtual Description Description { get; set; }
    }
}
