//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkinCareWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SkinCareDBEntities : DbContext
    {
        public SkinCareDBEntities()
            : base("name=SkinCareDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionData> ActionDatas { get; set; }
        public virtual DbSet<Description> Descriptions { get; set; }
        public virtual DbSet<AssessmentRespons> AssessmentResponses { get; set; }
        public virtual DbSet<DescriptionType> DescriptionTypes { get; set; }
        public virtual DbSet<TrendsArchiveData> TrendsArchiveDatas { get; set; }
        public virtual DbSet<TrendsMapData> TrendsMapDatas { get; set; }
    }
}
