//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkinCareWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrendsMapData
    {
        public int Id { get; set; }
        public string LocationCityName { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Long { get; set; }
        public Nullable<long> TrendStartDate { get; set; }
        public Nullable<long> TrendEndDate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
