//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkinCareWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrendsArchiveData
    {
        public int Id { get; set; }
        public long EpochDate { get; set; }
        public Nullable<double> Temp { get; set; }
        public Nullable<double> Humidity { get; set; }
        public Nullable<double> SolarRadiation { get; set; }
        public Nullable<double> SolarEnergy { get; set; }
        public Nullable<double> UvIndex { get; set; }
    }
}
